### ISSUE TITLE
Optimize Preprocess_json()

### ISSUE THREAD

**Issue by diego-lopez8** [zoe70416/NIDS#20]
There are a lot of optimizations we can make to the `preprocess_json()` function. Because we are already selecting on the fields in the `makedf_samecol()` function, there is less of a need to spend cycles actually dropping columns from the dataframe. We should try to clean up as much of these as possible. 

The end goal should be changing everything to numpy. That is not this ticket, lets just make pandas run as fast as we can before spending enormous energy changing it to numpy.

**Comment by diego-lopez8** [comment]
please also clean up the comments as the TODOs are mostly completed

**Comment by zoe70416** [comment]
@diego-lopez8  Can I remove the code (from last semester) that we're not using?

**Comment by diego-lopez8** [comment]
Yes!

**Comment by zoe70416** [comment]
@diego-lopez8 Done. Please check the latest PR.

**Comment by diego-lopez8** [comment]
completed
