### ISSUE TITLE
Research ML Systems that influence their own data acquisition

### ISSUE THREAD

**Issue by diego-lopez8** [zoe70416/NIDS#21]
We are developing a ML system that will influence its own data acquisition quite heavily. 

Consider the following scenario:

Suppose our system by default has a mirror ACL that says that it will only mirror traffic from Port 443 (HTTPS) and 22 (SSH) by default. These are pretty normal and well used services. This necessarily means that all the other ports will NOT be mirrored, such as say port 25 (SMTP). Suppose an anomaly is detected on 443 and suddenly the ML system decides to mirror everything from a node, and now suddenly sees port 25 traffic which has a different distribution from what the port 443 traffic is. This presents a problem in multiple ways: firstly, if suddenly port 25 traffic is mirrored and this has not been seen before by the system, it will think its anomalous as it would only consider port 443 and 22 traffic distributions in training, and thus when the ML system uses anomaly scores to influence what data to mirror, it may get stuck in a loop where it wants to see everything because everything is new to it.

This is solvable by adding a caveat to the usage of the system such that we require say some amount of time where the ACLs must mirror everything so the system can learn the environment. We could say this is required as a bootstrap when this system is first implemented in a network, however suppose now we want to retrain a model for the second time or 3rd onwards. The training data now includes the normal baseline ACL data that is always mirrored, as well as anomalous traffic that the ML system mirrored on its own, ie the data the ML system influenced the network to mirror. How should this 2nd training work? Are there any methods we can use? Or would we need to bootstrap with a full data view again?

**Comment by olive-jy-song** [comment]
I have a couple of stupid questions about computer networks: 

1. May I confirm that the inference of anomaly scores happens before mirroring? i.e. the detector sits on the ERSPAN thing, which first infers the anomaly scores of the incoming flows, and then updates the ACL, if necessary; then the selected flows will be mirrored. 

2. May I then confirm that we can only access the mirrored flows during training (either online or offline).  

3. How many ports do we need to select from, and how many can we select to maintain the bandwidth? Is the selection by ports only?

**Comment by diego-lopez8** [comment]
1. We first will have to configure the switch with some baseline ACL to mirror to the anomaly detector, such as say mirroring all flows from the subnet 192.168.0.0/24 with traffic from 443 and 22. The NIDS then does inference on the flows matching from that subnet going to any devices port 443 or 22. If inference results in an anomaly being detected, then NIDS will go and say to the switch to alter the ACL so instead of mirroring 443 and 22, mirror everything matching that subnet.
2. I dont particularly follow, but you can access the flows at any time really. Because they will show up in the `current/conn.log` where you can see them for inference, but then after an hour they get put in the historical data
3. We can select not only by port but also by IP address, IP subnet, All UDP, UDP ports, TCP ports, All TCP, these tcp flags
```
established | [fin | not-fin] [syn | not-syn] [rst | not-rst] [psh | not-psh] [ack | not-ack] [urg | not-urg]
```
and ICMP (pings and such)

I would say we should probably use ports and addresses mostly

There isnt a number of ports specifically, just which ever ones we think are important, ie we can decide (or we can say its a parameter of the network). similarly, the bandwidth question is entirely dependent on the distributions of the network as well. for example a enterprise network may consist almost entirely of http traffic (80/443 ports). So we can decide, and we will have to figure that out in the experiments as well which to mirror and which to not mirror and their impact on bandwidth

**Comment by olive-jy-song** [comment]
Thank you!! It makes a lot more sense now. 

For 2., I guess I still don't get the point of mirroring yet. How it is different from just accessing the conn.log? What do we use the mirrored flows for? According to 1., at least they go through the inference. I used to be thinking that we can only access the mirrored flows during training, and that's why our selection would affect the future training data. 

For 1., if my understanding is correct, we only mirror parts of the subnet, and use these partial flows to check if there's anomaly, following: 
a) We start from some baseline ACL, open to future updates, and mirror let's say certain ports of a subnet. 
b) Only these mirrored flows will go through inference and have corresponding anomaly scores. 
c) If any of the flows is checked as anomalous (either solely by the score or jointly by experts I guess), everything from that subnet from this point on will be mirrored. 

If this is the case, I have some other confusions: 
4. How would mirroring everything future flow from that subnet help? Why would this be necessary and a good thing for cybersecurity? 
5. Will there be any delays in terms of ACL update? (this is trivial though I guess) 
6. From a cybersecurity perspective, do we know for how long we should mirror everything from that subnet? (I guess this relates to 4 as well, and probably relates to our ACL update regime) 
7. Wouldn't mirroring everything from the subnet takes up resources from other subnets, while maintaining the bandwidth level? Or, do we sacrifice the bandwidth in these cases?  

I apologize for so many questions... Thank you so much for your patience!!

**Comment by diego-lopez8** [comment]
![erspan_research drawio](https://github.com/zoe70416/NIDS/assets/65259932/8992cd61-da28-4003-b960-15b08b185ea4)
2. Take a look at this diagram. This is a "spine-leaf" architecture used in many datacenters. Consider this a 2 rack data center with 3 hosts in each rack. Each rack has 2 leaf switches (called Top of Rack switches). I drew the redundancy so you can see what this actually looks like in a real deploy, where each host / server connects to both leaf switches for redundancy, and also the leafs connect to multiple spines for redundancy. For a packet to get from a host in 1 rack to a host in another rack, the packet would go up to a leaf (not important really which one), then to the spine, then down to the leaf in the destination rack, then to the host. If a packet is going to the internet from a host, it would go to the leaf, then to the spine, then to the edge gateway, then out to the ISP. As you can see, the NIDS can only see what is on the link between itself and the switch. For example, if the NIDS sent a packet to google and google replies, Zeek, sniffing that link, would see that. If a host in the other rack would send a packet to google, the NIDS would NOT see that, because how could it? Its on a completely different switch. The way we get data that Host 1 for example is sending to Host 2 is through ERSPAN. Say Host 1 sends a packet to host 2 and we configure ERSPAN on all the leafs. The packet would hit a leaf, then get mirrored over ERSPAN, so 2 packets now go over the link to a spine. One of those then goes to its destination, and the other now goes to the NIDS where we can see what just happened. Zeek analyzes that and produces its conn.log on that data, even though it was a packet not intended for the NIDS. This is called "promiscuous sniffing" of the wire, IE making Zeek pay attention to stuff thats not intended for the host its sitting on. The bandwidth we are very much concerned with is the bandwidth from leaf to spine. If we mirror EVERYTHING to the NIDS now that 400 gig link becomes 200 because 2 packets leave the leaf instead of 1 now for every packet. So we need to tell ERSPAN to give us less data when the data is normal, and more when we see its anomalous. 
Regarding training / inference, everything on inference is being sent from ERSPAN from the switches. If we decide to tell all the switches to turn off ERSPAN, suddenly the NIDS would not receive anything. Historical data in this sense is data that the organization may have had beforehand from say only monitoring internet traffic. OR (what i think may be a necessary caveat) is that in our deployment specification, we say in order to use this system, you have to mirror a large amount of data to zeek without inference to get historical data first for a couple weeks or however long is necessary to reduce the variance in the environment / develop a baseline normal. At that point now you can put a baseline ACL to cut down the traffic..


Your A B C is correct.

4. As you correctly articulated, we are only mirroring from some ports by default, noted as the "baseline ACL". Suppose we see that some flows are anomalous, like we see a 443 HTTP connection go to a host in Russia and its never done that before. Why we suddenly want to mirror everything is that before, we operate under the idea that the host is functioning normally, and thus we dont need to expend bandwidth to monitor it. After we see anomalies cross a arbitrary threshold we determine, the state of the system now changes, where we see this behavior is anomalous and now we are willing to spend bandwidth in exchange for all the information we can get from this anomalous host because we want to know exactly what its doing from a network perspective. It could be sending packets over another protocol or port, say 555, that we would not have seen before. By getting everything now, we can have all that forensic data for downstream human analysis (a security engineer manually going through alerts now is able to see absolutely everything, when before they could not have if they had not altered the ACL. We can see if this host is sending data to other hosts, or in other words, potentially propagating throughout the network and infecting other hosts. 
5. ACL updates are trivial, its a simple HTTPS request to an endpoint on the switch with the data being the updated ACL we want to use for ERSPAN.
6. We do not, this would depend on an environment, but its something thats a spectrum / can be optimized. As we keep the mirror on, we expend bandwidth, but we are also still performing inference in real time. If we see that the target host continues to have anomalous flows, we want to keep spending bandwidth to capture them. However, if we note the machine slowly goes back to normal and does less scary things, we re examine the trade off in the system to conserve bandwidth again.
7. Im not entirely sure what you mean by resources, mirroring traffic from one subnet would not eat computational power really, but it would eat bandwidth. This could affect other subnets if the traffic from those other subnets is destined for the subnet we are mirroring. In terms of resources on the NIDS itself like CPU, this is another dimension which for now we should not dive into

No problem on the questions! Keep asking them. We wont be able to do good research unless everyone knows whats happening :)

**Comment by diego-lopez8** [comment]
cc @Zihang-Xia @zoe70416

**Comment by diego-lopez8** [comment]
Also a FYI, most institutions would simply put a NIDS connected to the edge gateway and SPAN mirror the couple of links going out to the ISP, so it captures all traffic to and from the internet. This is a decent approach but it captures none of the traffic between the racks. Traffic to and from internet is called "North South" traffic, traffic between hosts or racks in this sense is "East West" traffic. The benefit of the proposal is that we can monitor the entire datacenter or network with 1 NIDS in a bandwidth efficient manner, whereas before people could really only monitor north south via connecting a NIDS to the edge gateway and knowingly not monitoring east west. They could hypothetically connect a NIDS to each leaf and monitor the connections from leaf to spine, but that is extremely costly because you need another node in each rack (adds up quickly in terms of $), or you can ERSPAN everything and crush your network, or you can ERSPAN with a ACL and have a deterministic gap in your network (say i mirror port 443 but not 555, now an attacker can use 555 and i will never see it), but no system in research proposed to change this in real time or change it based on intelligence from the data.

**Comment by diego-lopez8** [comment]
For now, we decided we do not need to do online learning, so this issue will be closed

**Comment by zoe70416** [comment]
![428969853_24840792158900528_6637620715309538003_n](https://github.com/zoe70416/NIDS/assets/112972336/49840b11-0cff-4c49-bb19-da977807402c)
![429411401_786116736753800_62907271146394653_n](https://github.com/zoe70416/NIDS/assets/112972336/aaafeeb1-bc5d-483d-8560-bad20e36b0ab)

Meeting notes from Feb 22, 2024
